<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Miha Likar">

<title>Long Beach Animal Shelter - EDA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="lbas_eda_reg_likar_files/libs/clipboard/clipboard.min.js"></script>
<script src="lbas_eda_reg_likar_files/libs/quarto-html/quarto.js"></script>
<script src="lbas_eda_reg_likar_files/libs/quarto-html/popper.min.js"></script>
<script src="lbas_eda_reg_likar_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="lbas_eda_reg_likar_files/libs/quarto-html/anchor.min.js"></script>
<link href="lbas_eda_reg_likar_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="lbas_eda_reg_likar_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="lbas_eda_reg_likar_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="lbas_eda_reg_likar_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="lbas_eda_reg_likar_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Long Beach Animal Shelter - EDA</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Miha Likar </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'scales'

The following object is masked from 'package:purrr':

    discard

The following object is masked from 'package:readr':

    col_factor</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(paletteer)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(treemapify)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>In this report, I’ll present exploratory data analysis of Long Beach Animal Shelter dataset. Additionally, throughout the EDA, I will formulate specific research question(s) which will be addressed in the regression models section.</p>
<p>The workflow and structure of this report is as follows:</p>
<ul>
<li>Brief introduction about the dataset and available variables</li>
<li>Explore distributions of various single variables</li>
<li>Explore associations between 2 and/or more variables</li>
<li>Impute certain variables based on the available data (age, reproductive status)</li>
<li>Clearly formulate RQ and Hs</li>
<li>Regression analysis (model comparison)</li>
</ul>
</section>
<section id="exploratory-data-analysis-eda" class="level1">
<h1>Exploratory data analysis (EDA)</h1>
<section id="reading-the-dataset" class="level2">
<h2 class="anchored" data-anchor-id="reading-the-dataset">Reading the dataset</h2>
<p>Read the data from an online source - TidyTuesday GitHub page.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>longbeach_raw <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="st">'https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-03-04/longbeach.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 29787 Columns: 22
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (15): animal_id, animal_name, animal_type, primary_color, secondary_col...
dbl   (2): latitude, longitude
lgl   (2): outcome_is_dead, was_outcome_alive
date  (3): dob, intake_date, outcome_date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<p>Let’s look at the dataset, to see what we are working with.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(longbeach_raw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 29,787
Columns: 22
$ animal_id         &lt;chr&gt; "A693708", "A708149", "A638068", "A639310", "A618968…
$ animal_name       &lt;chr&gt; "*charlien", NA, NA, NA, "*morgan", "*brandon", NA, …
$ animal_type       &lt;chr&gt; "dog", "reptile", "bird", "bird", "cat", "rabbit", "…
$ primary_color     &lt;chr&gt; "white", "brown", "green", "white", "black", "black"…
$ secondary_color   &lt;chr&gt; NA, "green", "red", "gray", "white", "white", NA, "b…
$ sex               &lt;chr&gt; "Female", "Unknown", "Unknown", "Unknown", "Female",…
$ dob               &lt;date&gt; 2013-02-21, NA, NA, NA, 2014-12-18, 2023-04-19, NA,…
$ intake_date       &lt;date&gt; 2023-02-20, 2023-10-03, 2020-01-01, 2020-02-02, 201…
$ intake_condition  &lt;chr&gt; "ill mild", "normal", "injured  severe", "ill severe…
$ intake_type       &lt;chr&gt; "stray", "stray", "wildlife", "wildlife", "stray", "…
$ intake_subtype    &lt;chr&gt; "otc", "field", "field", "field", "field", "otc", "f…
$ reason_for_intake &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ outcome_date      &lt;date&gt; 2023-02-26, 2023-10-03, 2020-01-01, 2020-02-02, 201…
$ crossing          &lt;chr&gt; "[2600 BLK LONG BEACH BLVD, LONG BEACH CA, 90806", "…
$ jurisdiction      &lt;chr&gt; "Long Beach", "Long Beach", "Long Beach", "Long Beac…
$ outcome_type      &lt;chr&gt; "euthanasia", "rescue", "euthanasia", "transfer", "r…
$ outcome_subtype   &lt;chr&gt; "ill severe", "other resc", "inj severe", "lbah", "l…
$ latitude          &lt;dbl&gt; 33.80479, 33.86800, 33.76048, 33.76246, 33.84950, 33…
$ longitude         &lt;dbl&gt; -118.1889, -118.2009, -118.1481, -118.1597, -118.194…
$ outcome_is_dead   &lt;lgl&gt; TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE,…
$ was_outcome_alive &lt;lgl&gt; FALSE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, T…
$ geopoint          &lt;chr&gt; "33.8047935, -118.1889261", "33.8679994, -118.200930…</code></pre>
</div>
</div>
<p>There are several variables that already stand out as variables we want to primarily focus on in our EDA. These are:</p>
<ul>
<li><code>animal_type</code></li>
<li><code>sex</code></li>
<li><code>dob</code> + <code>intake_date</code></li>
<li><code>intake_condition</code></li>
<li><code>intake_type</code></li>
<li><code>outcome_date</code></li>
<li><code>outcome_type</code></li>
</ul>
<p>Before we proceed, let’s factorize all the character variables. If we realize we need some of them in the numeric or character format later on, we can change this afterwards.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>longbeach <span class="ot">&lt;-</span> longbeach_raw <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.character), as.factor))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Ok let’s look at the summary, get the basic idea of levels of categorical variables etc.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(longbeach)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   animal_id      animal_name     animal_type         primary_color 
 A637086:    8   *      :   92   cat    :14145   black       :7540  
 A637269:    7   luna   :   84   dog    : 9768   gray        :3916  
 A279626:    6   rocky  :   78   bird   : 2075   white       :3651  
 A610057:    6   max    :   77   wild   : 1412   brown       :3531  
 A354875:    5   coco   :   64   other  : 1332   brown  tabby:2242  
 A542375:    5   (Other):17230   rabbit :  526   tan         :1393  
 (Other):29750   NA's   :12162   (Other):  529   (Other)     :7514  
 secondary_color       sex            dob              intake_date        
 white  : 8344   Female  :6230   Min.   :1993-05-28   Min.   :2017-01-01  
 black  : 1902   Male    :6854   1st Qu.:2016-07-09   1st Qu.:2018-08-10  
 brown  : 1402   Neutered:5588   Median :2018-11-01   Median :2020-08-29  
 tan    :  830   Spayed  :4763   Mean   :2018-08-09   Mean   :2020-11-17  
 gray   :  783   Unknown :6352   3rd Qu.:2022-02-01   3rd Qu.:2023-04-19  
 (Other):  922                   Max.   :2031-03-30   Max.   :2024-12-31  
 NA's   :15604                   NA's   :3591                             
          intake_condition          intake_type     intake_subtype 
 normal           :13706   stray          :21126   otc     :15519  
 under age/weight : 6590   wildlife       : 4473   field   :11818  
 injured  severe  : 2097   owner surrender: 2615   trap    :  468  
 ill severe       : 1311   welfare seized :  484   police  :  374  
 ill mild         : 1192   confiscate     :  399   adoption:  220  
 injured  moderate: 1177   return         :  306   (Other) :  998  
 (Other)          : 3714   (Other)        :  384   NA's    :  390  
  reason_for_intake  outcome_date       
 owner prob:  432   Min.   :2017-01-01  
 move      :  236   1st Qu.:2018-08-18  
 landlord  :  145   Median :2020-09-01  
 cost      :  133   Mean   :2020-11-27  
 no time   :  122   3rd Qu.:2023-04-21  
 (Other)   :  935   Max.   :2024-12-31  
 NA's      :27784   NA's   :177         
                                               crossing    
 7700 E SPRING ST, LONG BEACH, CA 90815            :  251  
 7700 BLK E SPRING ST, LONG BEACH, CA 90815        :   70  
 6400 BLK ATLANTIC AVE, LONG BEACH, CA 90805       :   68  
 3300 BLK SANTA FE AVE, LONG BEACH, CA 90810       :   50  
 7500 BLK E SPRING ST, LONG BEACH, CA 90815        :   50  
 4700 BLK E PACIFIC COAST HWY, LONG BEACH, CA 90804:   45  
 (Other)                                           :29253  
       jurisdiction            outcome_type    outcome_subtype     latitude    
 Long Beach  :25590   rescue         :6680   spcala    : 3784   Min.   :19.30  
 Cerritos    : 2023   adoption       :6290   walkin    : 2857   1st Qu.:33.78  
 Signal Hill :  721   euthanasia     :5451   web       : 2852   Median :33.81  
 Los Alamitos:  531   transfer       :4869   ill severe: 1869   Mean   :33.81  
 Seal Beach  :  373   return to owner:3214   inj severe: 1286   3rd Qu.:33.85  
 (Other)     :  548   (Other)        :3096   (Other)   :13753   Max.   :45.52  
 NA's        :    1   NA's           : 187   NA's      : 3386                  
   longitude       outcome_is_dead was_outcome_alive
 Min.   :-122.70   Mode :logical   Mode :logical    
 1st Qu.:-118.19   FALSE:23573     FALSE:6214       
 Median :-118.17   TRUE :6214      TRUE :23573      
 Mean   :-118.15                                    
 3rd Qu.:-118.13                                    
 Max.   : -73.99                                    
                                                    
                     geopoint    
 33.8096122, -118.0826161:  456  
 33.7700504, -118.1937395:  135  
 33.8708354, -118.1846106:  118  
 33.8097185, -118.0929813:  108  
 33.7898537, -118.1458794:  101  
 33.810379, -118.0992327 :   73  
 (Other)                 :28796  </code></pre>
</div>
</div>
<p><strong>Looking at the data, I notice a few things, that I should do, focus on:</strong></p>
<ul>
<li><code>animal_type</code>: lump, investigate distribution.</li>
<li><code>sex</code>: we can use this variable to infer both sex of the animal and “reproductive state” - whether animal was neutered/spayed, or it animal’s reproductive functioning is intact. Ivestigate distribution.</li>
<li>Use <code>dob</code> (date of birth) and <code>intake_date</code> to compute age at intake. This might be useful for modeling later on, but initially look at the distribution.</li>
<li>Investigate <code>intake_condition</code>. Probably categories will need lumping. Explore distribution.</li>
<li>Investigate <code>intake_type</code>. Probably categories will need lumping. Explore distribution.</li>
<li>Investigate <code>outcome_type</code>. Probably categories will need lumping. Explore distribution. Group the general types into <em>positive outcomes</em> and <em>negative outcomes</em> (will be discussed in more details later) and <em>adoption rate</em>, based on adopted vs.&nbsp;all other outcome types.</li>
</ul>
</section>
<section id="exploring-distributions-of-variables-of-interest" class="level2">
<h2 class="anchored" data-anchor-id="exploring-distributions-of-variables-of-interest">Exploring distributions of variables of interest</h2>
<section id="animal-type" class="level3">
<h3 class="anchored" data-anchor-id="animal-type">Animal type</h3>
<p>Let’s first check the levels of the variable <code>animal_type</code> and their count, and consider possible lumping strategies.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(animal_type)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   animal_type     n
   &lt;fct&gt;       &lt;int&gt;
 1 amphibian       3
 2 bird         2075
 3 cat         14145
 4 dog          9768
 5 guinea pig    172
 6 livestock      10
 7 other        1332
 8 rabbit        526
 9 reptile       344
10 wild         1412</code></pre>
</div>
</div>
<p>While it is possible that we would use lumping immediately to identify the most frequent animal types (either by fixed number of levels or proportion of the level vs.&nbsp;total count), we can also merge them manually based on reasoning and supporting <em>literature</em>.</p>
<p>It was reasonable to expect that cats and dogs will be the most prevalent categories. They are followed by birds. Category wild follows and category other is tightly behind. It seems legitimate to keep these levels as they are at this point. Rabbits and guinea pigs could be collapsed into category “Small mammals”. Reptiles and amphibians could be collapsed into “Exotic”, a type frequently used by shelters, pet stores etc. Livestock can definitely be merged with other, considering the group size of the livestock.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>longbeach <span class="ot">&lt;-</span> longbeach <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">animal_type =</span> <span class="fu">fct_collapse</span>(animal_type,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">Dogs =</span> <span class="st">"dog"</span>,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">Cats =</span> <span class="st">"cat"</span>,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">Birds =</span> <span class="st">"bird"</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">Wildlife =</span> <span class="st">"wild"</span>,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">`</span><span class="at">Small mammals</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"rabbit"</span>, <span class="st">"guinea pig"</span>),</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">Exotic =</span> <span class="fu">c</span>(<span class="st">"reptile"</span>,<span class="st">"amphibian"</span>),</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>                                   <span class="at">Other =</span> <span class="fu">c</span>(<span class="st">"other"</span>, <span class="st">"livestock"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>These are the categories that we will work with throughout EDA. I can anticipate that perhaps only dogs and cats will be features in the regression models due to significant discrepancy in sub-sample size of these two categories, compared to smaller ones such as birds, wildlife etc. Dataset documentation does not provide precise information about the group “Other”. It is possible that various different species are included in this type.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(animal_type, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 2
  animal_type       n
  &lt;fct&gt;         &lt;int&gt;
1 Cats          14145
2 Dogs           9768
3 Birds          2075
4 Wildlife       1412
5 Other          1342
6 Small mammals   698
7 Exotic          347</code></pre>
</div>
</div>
<p>We can use this variable for some basic distribution/count visualisation now.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jcolors)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(paletteer)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpomological)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span> </span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(animal_type) <span class="sc">%&gt;%</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">animal_type =</span> <span class="fu">fct_reorder</span>(animal_type, n)) <span class="sc">%&gt;%</span> </span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> animal_type, <span class="at">y =</span> n, <span class="at">fill =</span> animal_type)) <span class="sc">+</span> </span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span> </span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span> </span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Number of animals"</span>, <span class="at">title =</span> <span class="st">"Number of animals taken in by animal type (Long Beach Animal Shelter, 2017–2024)"</span>, <span class="at">caption =</span> <span class="st">"Small mammals include rabbits and guneia pigs. Exotic includes reptiles and amphibians."</span>, <span class="at">fill =</span> <span class="st">"Animal type"</span>) <span class="sc">+</span> </span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">15000</span>,<span class="dv">2500</span>)) <span class="sc">+</span> </span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  <span class="co">#scale_fill_brewer(palette = "Spectral", guide = guide_legend(reverse = TRUE)) +</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>  <span class="co">#scale_fill_dutchmasters(palette = "milkmaid") + </span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>  <span class="co">#scale_fill_pomological() + </span></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>  <span class="co">#scale_fill_paletteer_d("PrettyCols::Autumn") +</span></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>  <span class="co">#scale_fill_jcolors(palette = "pal7") + </span></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_paletteer_d</span>(<span class="st">"ggthemes::Tableau_10"</span>) <span class="sc">+</span></span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title.position =</span> <span class="st">"plot"</span>,</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.5</span>),</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position=</span><span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lbas_eda_reg_likar_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Consider removing the legend</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can play around a little bit and try so called “lollipop” visualization, as it has been said to be a more modern, appealing version of bar charts.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(animal_type) <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">animal_type =</span> <span class="fu">fct_reorder</span>(animal_type, n)) <span class="sc">%&gt;%</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> n, <span class="at">y =</span> animal_type)) <span class="sc">+</span> </span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">0</span>, <span class="at">xend =</span> n, <span class="at">yend =</span> animal_type, <span class="at">color =</span> animal_type), <span class="at">linewidth =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> animal_type), <span class="at">size =</span> <span class="dv">10</span>) <span class="sc">+</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> n), <span class="at">color =</span> <span class="st">"#313131"</span>, <span class="at">size =</span> <span class="fl">2.5</span>) <span class="sc">+</span> </span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="cn">NULL</span>, <span class="at">x =</span> <span class="st">"Number of animals"</span>, <span class="at">title =</span> <span class="st">"Number of animals taken in by animal type (Long Beach Animal Shelter, 2017–2024)"</span>, <span class="at">caption =</span> <span class="st">"Small mammals include rabbits and guneia pigs. Exotic includes reptiles and amphibians."</span>, <span class="at">fill =</span> <span class="st">"Animal type"</span>) <span class="sc">+</span> </span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">15000</span>,<span class="dv">2500</span>)) <span class="sc">+</span> </span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title.position =</span> <span class="st">"plot"</span>,</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.5</span>),</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position=</span><span class="st">"none"</span>) <span class="sc">+</span> </span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_paletteer_d</span>(<span class="st">"ggthemes::Tableau_10"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lbas_eda_reg_likar_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I want to play around with different visualizations a bit and thought that while bar chart might be very simple to read and informative for both an advanced as well as lay reader, I can try out treemaps.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(treemapify)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(animal_type) <span class="sc">%&gt;%</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">label_size =</span> <span class="fu">rescale</span>(n, <span class="at">to =</span> <span class="fu">c</span>(<span class="dv">8</span>, <span class="dv">60</span>))) <span class="sc">%&gt;%</span>  <span class="co"># scale size between 3 and 8</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">area =</span> n, <span class="at">fill =</span> animal_type, <span class="at">label =</span> <span class="fu">paste0</span>(animal_type, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>, n))) <span class="sc">+</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_treemap</span>() <span class="sc">+</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_treemap_text</span>(<span class="fu">aes</span>(<span class="at">size =</span> label_size), <span class="at">colour =</span> <span class="st">"#474747"</span>, <span class="at">place =</span> <span class="st">"centre"</span>, <span class="at">grow =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_size_identity</span>() <span class="sc">+</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_paletteer_d</span>(<span class="st">"ggthemes::Tableau_10"</span>) <span class="sc">+</span> </span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Number of animals taken in by animal type </span><span class="sc">\n</span><span class="st">(Long Beach Animal Shelter, 2017–2024)"</span>, <span class="at">subtitle =</span> <span class="st">"Area of each type represents proportion of the total intake."</span>, <span class="at">caption =</span> <span class="st">"Small mammals include rabbits and guneia pigs. Exotic includes reptiles and amphibians."</span>) <span class="sc">+</span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title.position =</span> <span class="st">"plot"</span>,</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.05</span>),</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position=</span><span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_fixed</span>(<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lbas_eda_reg_likar_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Fine for now. We can always return to these graphs and polish the appearance. We can now apply the same logic to investigate other variables!</p>
<p>###Intake condition</p>
<p>Let’s first check the levels of the variable <code>intake_condition</code> and their count, and consider possible lumping strategies.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(intake_condition, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 17 × 2
   intake_condition       n
   &lt;fct&gt;              &lt;int&gt;
 1 normal             13706
 2 under age/weight    6590
 3 injured  severe     2097
 4 ill severe          1311
 5 ill mild            1192
 6 injured  moderate   1177
 7 injured  mild       1093
 8 ill moderatete       942
 9 fractious            654
10 feral                283
11 i/i report           249
12 aged                 156
13 behavior  moderate   127
14 behavior  severe      70
15 welfare seizures      70
16 behavior  mild        69
17 intakeexam             1</code></pre>
</div>
</div>
<p>Huh, alright, there are 17 different conditions. It appears that we could collapse illness and injury together in “physical condition”. Let’s explore lumping a bit, with fixed number of categories and proportions of total sample.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Fixed number of categories</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">intake_condition =</span> <span class="fu">fct_lump</span>(intake_condition, <span class="at">n =</span> <span class="dv">10</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(intake_condition, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 2
   intake_condition      n
   &lt;fct&gt;             &lt;int&gt;
 1 normal            13706
 2 under age/weight   6590
 3 injured  severe    2097
 4 ill severe         1311
 5 ill mild           1192
 6 injured  moderate  1177
 7 injured  mild      1093
 8 ill moderatete      942
 9 Other               742
10 fractious           654
11 feral               283</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Number of categories based on proportions</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">intake_condition =</span> <span class="fu">fct_lump</span>(intake_condition, <span class="at">prop =</span> .<span class="dv">03</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(intake_condition, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 2
  intake_condition      n
  &lt;fct&gt;             &lt;int&gt;
1 normal            13706
2 under age/weight   6590
3 injured  severe    2097
4 Other              1679
5 ill severe         1311
6 ill mild           1192
7 injured  moderate  1177
8 injured  mild      1093
9 ill moderatete      942</code></pre>
</div>
</div>
<p><strong>Based on category inspection I decided the following:</strong></p>
<ul>
<li>merge illness and injury in “physical” category</li>
<li>I am also considering joining with behavioral (mild, moderate, severe) or collapsing these categories into “other” as the number of observations is really small</li>
<li>There seem to be some specific smaller categories (aged, welfare seizures etc.), which will be collapsed into “other”.</li>
</ul>
<p>We need to collapse the categories manually.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>longbeach <span class="ot">&lt;-</span> longbeach <span class="sc">%&gt;%</span> </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">intake_condition =</span> <span class="fu">fct_lump</span>(intake_condition, <span class="dv">10</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">intake_condition =</span> <span class="fu">fct_collapse</span>(intake_condition,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">Normal =</span> <span class="st">"normal"</span>,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">`</span><span class="at">Mild physical</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"ill mild"</span>, <span class="st">"injured  mild"</span>),</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">`</span><span class="at">Moderate physical</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"ill moderatete"</span>, <span class="st">"injured  moderate"</span>),</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">`</span><span class="at">Severe physical</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"ill severe"</span>, <span class="st">"injured  severe"</span>),</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>                                         <span class="st">`</span><span class="at">Under age/weight</span><span class="st">`</span> <span class="ot">=</span> <span class="st">"under age/weight"</span>,,</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>                                         <span class="at">other_level =</span> <span class="st">"Other"</span>))</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span> </span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(intake_condition, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  intake_condition      n
  &lt;fct&gt;             &lt;int&gt;
1 Normal            13706
2 Under age/weight   6590
3 Severe physical    3408
4 Mild physical      2285
5 Moderate physical  2119
6 Other              1679</code></pre>
</div>
</div>
<p>First, I will specify colors associated with each category, so they remain the same throughout visualisations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>intake_colors <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Normal"</span> <span class="ot">=</span> <span class="st">"#77b7b2"</span>,</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Mild physical"</span> <span class="ot">=</span> <span class="st">"#ebcb2a"</span>,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Moderate physical"</span> <span class="ot">=</span> <span class="st">"#f28d2b"</span>,</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Severe physical"</span> <span class="ot">=</span> <span class="st">"#e15859"</span>,</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Under age/weight"</span> <span class="ot">=</span> <span class="st">"#c8868d"</span>,</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Other"</span> <span class="ot">=</span> <span class="st">"#cbc8c5"</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s now use same visualizations as before for <code>animal_type</code> to plot distribution of <code>intake_condition</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span> </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(intake_condition) <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">intake_condition =</span> <span class="fu">fct_reorder</span>(intake_condition, n)) <span class="sc">%&gt;%</span> </span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> intake_condition, <span class="at">y =</span> n, <span class="at">fill =</span> intake_condition)) <span class="sc">+</span> </span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span> </span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span> </span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Intake condition"</span>, <span class="at">y =</span> <span class="st">"Number of animals"</span>, <span class="at">title =</span> <span class="st">"Number of animals taken in, by intake condition </span><span class="sc">\n</span><span class="st">(Long Beach Animal Shelter, 2017–2024)"</span>, <span class="at">caption =</span> <span class="st">"Physical conditions include illnesses and injuries."</span>, <span class="at">fill =</span> <span class="st">"Intake condition"</span>) <span class="sc">+</span> </span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">15000</span>,<span class="dv">2500</span>)) <span class="sc">+</span> </span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> intake_colors) <span class="sc">+</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title.position =</span> <span class="st">"plot"</span>,</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.3</span>),</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position=</span><span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lbas_eda_reg_likar_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Consider removing the legend</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can play around a little bit and try so called “lollipop” visualization, as it has been said to be a more modern, appealing version of bar charts.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span> </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(intake_condition) <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">intake_condition =</span> <span class="fu">fct_reorder</span>(intake_condition, n)) <span class="sc">%&gt;%</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> n, <span class="at">y =</span> intake_condition)) <span class="sc">+</span> </span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">0</span>, <span class="at">xend =</span> n, <span class="at">yend =</span> intake_condition, <span class="at">color =</span> intake_condition), <span class="at">linewidth =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> intake_condition), <span class="at">size =</span> <span class="dv">11</span>) <span class="sc">+</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> n), <span class="at">color =</span> <span class="st">"#313131"</span>,  <span class="at">size =</span> <span class="fl">2.5</span>) <span class="sc">+</span> </span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="cn">NULL</span>, <span class="at">x =</span> <span class="st">"Number of animals"</span>, <span class="at">title =</span> <span class="st">"Number of animals taken in, by intake condition </span><span class="sc">\n</span><span class="st">(Long Beach Animal Shelter, 2017–2024)"</span>, <span class="at">caption =</span> <span class="st">"Physical conditions include illnesses and injuries."</span>, <span class="at">fill =</span> <span class="st">"Animal type"</span>) <span class="sc">+</span> </span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">15000</span>,<span class="dv">5000</span>)) <span class="sc">+</span> </span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title.position =</span> <span class="st">"plot"</span>,</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.3</span>),</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position=</span><span class="st">"none"</span>) <span class="sc">+</span> </span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> intake_colors)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lbas_eda_reg_likar_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>I want to play around with different visualizations a bit and thought that while bar chart might be very simple to read and informative for both an advanced as well as lay reader, I can try out treemaps.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(treemapify)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(intake_condition) <span class="sc">%&gt;%</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">label_size =</span> <span class="fu">rescale</span>(n, <span class="at">to =</span> <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">40</span>))) <span class="sc">%&gt;%</span>  <span class="co"># scale size between 3 and 8</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">area =</span> n, <span class="at">fill =</span> intake_condition, <span class="at">label =</span> <span class="fu">paste0</span>(intake_condition, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>, n))) <span class="sc">+</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_treemap</span>() <span class="sc">+</span></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_treemap_text</span>(<span class="fu">aes</span>(<span class="at">size =</span> label_size), <span class="at">colour =</span> <span class="st">"#474747"</span>, <span class="at">place =</span> <span class="st">"centre"</span>, <span class="at">grow =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_size_identity</span>() <span class="sc">+</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> intake_colors) <span class="sc">+</span> </span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Number of animals taken in, by intake condition </span><span class="sc">\n</span><span class="st">(Long Beach Animal Shelter, 2017–2024)"</span>, <span class="at">subtitle =</span> <span class="st">"Area of each intake condition represents proportion of the total intake."</span>, <span class="at">caption =</span> <span class="st">"Physical conditions include illnesses and injuries."</span>) <span class="sc">+</span></span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title.position =</span> <span class="st">"plot"</span>,</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.05</span>),</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position=</span><span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_fixed</span>(<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lbas_eda_reg_likar_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From these plots we can see that the majority of the animals taken into the Long Beach Animal Shelter are in normal physical condition. About half less is animals that are under age or under weight. This is roughly compared to all three categories of hindered physical condition combined ~ mild, moderate, severe. <em>At this point I start thinking that intake condition might be an interesting predictor in the regression models. At this point we can plot <code>animal_type</code> and <code>intake_condition</code> together and explore in what conditions are different animals usually taken into the shelter.</em></p>
<section id="combining-animal-type-and-intake-condition" class="level4">
<h4 class="anchored" data-anchor-id="combining-animal-type-and-intake-condition">Combining animal type and intake condition</h4>
<p>For each type of animal, what number/proportion of them arrived in each intake condition?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span> </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">animal_type =</span> <span class="fu">fct_relevel</span>(animal_type, <span class="st">"Other"</span>, <span class="st">"Wildlife"</span>, <span class="st">"Exotic"</span>, <span class="st">"Small mammals"</span>, <span class="st">"Birds"</span>, <span class="st">"Dogs"</span>, <span class="st">"Cats"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">intake_condition =</span> <span class="fu">fct_relevel</span>(</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  intake_condition,</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Other"</span>,</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Severe physical"</span>,</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Moderate physical"</span>,</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Mild physical"</span>,</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Under age/weight"</span>,</span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Normal"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> animal_type, <span class="at">fill =</span> intake_condition)) <span class="sc">+</span> </span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span> </span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Animal type"</span>, </span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Number of animals"</span>,</span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Number of animals with different intake conditions for each animal type </span><span class="sc">\n</span><span class="st">(Long Beach Animal Shelter, 2017–2024)"</span>,</span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Intake condition"</span>) <span class="sc">+</span> </span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> intake_colors, <span class="at">guide =</span> <span class="fu">guide_legend</span>(<span class="at">reverse =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lbas_eda_reg_likar_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>While this visualization is informative about absolute number of observations of each intake condition for different animal types. We again see that cats, followed by dogs dominate in overall number of intakes. Interesting observation is that there is quite a large proportion of cats taken in under-aged or under-weight condition. Majority of dogs on the other hand appear to be accepted in normal condition. It might also be good to visualize proportions within each group, to get an insight into more specific between-animal type differences, that might remain hidden in column-plotting with huge number of observations between the groups.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(animal_type <span class="sc">!=</span> <span class="st">"livestock"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">animal_type =</span> <span class="fu">fct_relevel</span>(animal_type, <span class="st">"Other"</span>, <span class="st">"Wildlife"</span>, <span class="st">"Exotic"</span>, <span class="st">"Small mammals"</span>, <span class="st">"Birds"</span>, <span class="st">"Dogs"</span>, <span class="st">"Cats"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">intake_condition =</span> <span class="fu">fct_relevel</span>(</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  intake_condition,</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Severe physical"</span>,</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Moderate physical"</span>,</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Mild physical"</span>,</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Other"</span>,</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Under age/weight"</span>,</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Normal"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> animal_type, <span class="at">fill =</span> intake_condition)) <span class="sc">+</span> </span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span> </span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Animal type"</span>, </span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Proportion of the specific intake condition (%)"</span>,</span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Proportion of specific intake condition for each animal type </span><span class="sc">\n</span><span class="st">(Long Beach Animal Shelter, 2017–2024)"</span>,</span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Intake condition"</span>) <span class="sc">+</span> </span>
<span id="cb36-19"><a href="#cb36-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span> </span>
<span id="cb36-20"><a href="#cb36-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb36-21"><a href="#cb36-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">labels =</span> <span class="fu">label_percent</span>(), </span>
<span id="cb36-22"><a href="#cb36-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.2</span>)) <span class="sc">+</span> </span>
<span id="cb36-23"><a href="#cb36-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> intake_colors, <span class="at">guide =</span> <span class="fu">guide_legend</span>(<span class="at">reverse =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lbas_eda_reg_likar_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>OK, let’s try a slightly different approach and tweak the plot by adding percentage scale on both side of the axis, order animal types based on percentage of normal intake condition and add total number of counts next to animal names.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Let's first pull the order of the names by proportion of normal intake condition - I tried doing it in the same pipeline, but it does not work</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>animal_order <span class="ot">&lt;-</span> longbeach <span class="sc">%&gt;%</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(animal_type, intake_condition) <span class="sc">%&gt;%</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(animal_type) <span class="sc">%&gt;%</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">type_n =</span> <span class="fu">sum</span>(n),</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">p =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n),</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">animal_type_lab =</span> <span class="fu">paste0</span>(animal_type, <span class="st">" ("</span>, type_n, <span class="st">")"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(intake_condition <span class="sc">==</span> <span class="st">"Normal"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(p) <span class="sc">%&gt;%</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(animal_type_lab)</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span> </span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(animal_type, intake_condition) <span class="sc">%&gt;%</span></span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(animal_type) <span class="sc">%&gt;%</span></span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">type_n =</span> <span class="fu">sum</span>(n)) <span class="sc">%&gt;%</span></span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">animal_type_lab =</span> <span class="fu">paste0</span>(animal_type, <span class="st">" ("</span>, type_n, <span class="st">")"</span>),</span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a>         <span class="at">animal_type_lab =</span> <span class="fu">factor</span>(animal_type_lab, <span class="at">levels =</span> animal_order),</span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a>         <span class="at">intake_condition =</span> <span class="fu">fct_relevel</span>(intake_condition,</span>
<span id="cb37-23"><a href="#cb37-23" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Severe physical"</span>,</span>
<span id="cb37-24"><a href="#cb37-24" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Moderate physical"</span>,</span>
<span id="cb37-25"><a href="#cb37-25" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Mild physical"</span>,</span>
<span id="cb37-26"><a href="#cb37-26" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Other"</span>,</span>
<span id="cb37-27"><a href="#cb37-27" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Under age/weight"</span>,</span>
<span id="cb37-28"><a href="#cb37-28" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Normal"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb37-29"><a href="#cb37-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> animal_type_lab, <span class="at">y =</span> n, <span class="at">fill =</span> intake_condition)) <span class="sc">+</span> </span>
<span id="cb37-30"><a href="#cb37-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span> </span>
<span id="cb37-31"><a href="#cb37-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb37-32"><a href="#cb37-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Animal type"</span>, </span>
<span id="cb37-33"><a href="#cb37-33" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Proportion of the specific intake condition (%)"</span>,</span>
<span id="cb37-34"><a href="#cb37-34" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Proportion of specific intake condition for each animal type </span><span class="sc">\n</span><span class="st">(Long Beach Animal Shelter, 2017–2024)"</span>, <span class="at">subtitle =</span> <span class="st">"Numbers next to the animal types represent number of individuals from that group."</span>,</span>
<span id="cb37-35"><a href="#cb37-35" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Intake condition"</span>) <span class="sc">+</span> </span>
<span id="cb37-36"><a href="#cb37-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span> </span>
<span id="cb37-37"><a href="#cb37-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb37-38"><a href="#cb37-38" aria-hidden="true" tabindex="-1"></a>  <span class="at">labels =</span> <span class="fu">label_percent</span>(), </span>
<span id="cb37-39"><a href="#cb37-39" aria-hidden="true" tabindex="-1"></a>  <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.2</span>),</span>
<span id="cb37-40"><a href="#cb37-40" aria-hidden="true" tabindex="-1"></a>  <span class="at">sec.axis =</span> <span class="fu">dup_axis</span>(<span class="at">labels =</span> <span class="fu">label_percent</span>(), <span class="at">name =</span> <span class="cn">NULL</span>)) <span class="sc">+</span> </span>
<span id="cb37-41"><a href="#cb37-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> intake_colors, <span class="at">guide =</span> <span class="fu">guide_legend</span>(<span class="at">reverse =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lbas_eda_reg_likar_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Considering this visualisation, there are few things we can think about:</p>
<ul>
<li>It seems that exotic animals and small mammals usually arrive/are accepted in normal condition. Possibly as they might escape from home for a short while and are registered into the system upon arrival, however owners potentially pick them up soon. Thus these are not animals that would linger the streets for a long time.</li>
<li>Dogs are admitted to the shelter in normal condition much more frequently compared to cats.</li>
<li>However, cats have really high proportion of under-aged or under-weight intakes. It is possible, that stray cats give birth prematurely more often compared to dogs. On the other hand, it is possible that survival on the streets is the hardest for cats, thus leaving a lot of members of the stray cat community under-fed and under-weight.</li>
<li>Birds and wildlife have high proportion of (severe) physical conditions. Perhaps a lot of members of these groups arrive to the shelter because of the injury in the first place. It is possible that wild animals roam into urban environment or that birds have all sorts of accidents and are then injured brought to the shelter by members of the community or taken in by members of the shelter.</li>
</ul>
</section>
</section>
<section id="intake-type" class="level3">
<h3 class="anchored" data-anchor-id="intake-type">Intake type</h3>
<p>Based on the points raised in the end of the previous section, we can consider looking into <code>intake_type</code> variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span> </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(intake_type, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 2
   intake_type               n
   &lt;fct&gt;                 &lt;int&gt;
 1 stray                 21126
 2 wildlife               4473
 3 owner surrender        2615
 4 welfare seized          484
 5 confiscate              399
 6 return                  306
 7 quarantine              162
 8 safe keep               130
 9 trap, neuter, return     73
10 euthenasia required      15
11 adopted animal return     2
12 foster                    2</code></pre>
</div>
</div>
<p>Majority of the animals are either stray or come from wildlife, and a noticeable proportion of animals being surrendered by the owner. Due to highly unbalanced groups, I will not explore this variable for now, will just check the count for each type of intake for different types of animals and visualize it.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(animal_type, intake_type) <span class="sc">%&gt;%</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">animal_type =</span> <span class="fu">fct_relevel</span>(animal_type,</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"Cats"</span>, <span class="st">"Dogs"</span>, <span class="st">"Small mammals"</span>, <span class="st">"Exotic"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(animal_type, n, <span class="at">fill =</span> intake_type) <span class="sc">%&gt;%</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span> </span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  <span class="co">#geom_col() + </span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Proportion of animals"</span>, <span class="at">x =</span> <span class="st">"Animal type"</span>, <span class="at">fill =</span> <span class="st">"Intake type"</span>, <span class="at">title =</span> <span class="st">"Proportion of animals by different intake types for each type of animal </span><span class="sc">\n</span><span class="st">(Long Beach Animal Shelter, 2017–2024)"</span>) <span class="sc">+</span> </span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_paletteer_d</span>(<span class="st">"ggthemes::Classic_Green_Orange_12"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lbas_eda_reg_likar_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Majority of dogs and cats in particular are stray animals and a noticeable percentage of animals in those groups coming by owner’s surrender. Birds, wildlife and other species are predominantly found in wild life, and presumably injured or ill, as discussed in the end of the previous section.</p>
</section>
<section id="sex" class="level3">
<h3 class="anchored" data-anchor-id="sex">Sex</h3>
<p>Let’s now proceed with the <code>sex</code> variable. During initial data inspection, I noticed that there are not only sex information, but also whether animal was neutered/spayed and is thus not sexually active/capable of reproduction anymore. As I am still seriously considering modeling adoption rate in regression models, this information might be valuable. Let’s first look into the variable, mutate it and visualize.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 2
  sex          n
  &lt;fct&gt;    &lt;int&gt;
1 Female    6230
2 Male      6854
3 Neutered  5588
4 Spayed    4763
5 Unknown   6352</code></pre>
</div>
</div>
<p>OK, I will leave category Unknown as it is. Then, I will split the original <code>sex</code> variable into two, one about sex and one about reproductive state. From the meaning of the words, we can infer then when the condition is “Neutered” it refers to the male, and when the condition is “Spayed”, it refers to the females. After looking into online forum discussion and consulting various AIs, I concluded that when reproductive status is listed, we can infer the sex. When it is not, we can conclude that the reproductive state is intact and biological sex is listed.</p>
<p>Based on this I will create binary variable <code>starilised</code>, which will be 1 if current <code>sex</code> is “Spayed” or “Neutered” and 0 if biological sex is listed. I will recode values in the original <code>sex</code> category to only include information about biological sex.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>longbeach <span class="ot">&lt;-</span> longbeach <span class="sc">%&gt;%</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sterilised =</span> <span class="fu">case_when</span>(sex <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Spayed"</span>, <span class="st">"Neutered"</span>) <span class="sc">~</span> <span class="st">"Yes"</span>,</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>                                sex <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Male"</span>, <span class="st">"Female"</span>) <span class="sc">~</span> <span class="st">"No"</span>,</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>                                sex <span class="sc">==</span> <span class="st">"Unknown"</span> <span class="sc">~</span> <span class="st">"Unknown"</span>),</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">sex =</span> <span class="fu">case_when</span>(sex <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Spayed"</span>, <span class="st">"Female"</span>) <span class="sc">~</span> <span class="st">"Female"</span>,</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>                                sex <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Male"</span>, <span class="st">"Neutered"</span>) <span class="sc">~</span> <span class="st">"Male"</span>,</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>                                sex <span class="sc">==</span> <span class="st">"Unknown"</span> <span class="sc">~</span> <span class="st">"Unknown"</span>))</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(sex, sterilised) <span class="sc">%&gt;%</span></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(sex, n, <span class="at">fill =</span> sterilised) <span class="sc">+</span> </span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>  <span class="co">#geom_col(position = "fill") + </span></span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Sex"</span>, <span class="at">y =</span> <span class="st">"Number of animals"</span>, <span class="at">fill =</span> <span class="st">"Sterilised"</span>, <span class="at">title =</span> <span class="st">"NUmber of sterilised and unstarilised animals by sex </span><span class="sc">\n</span><span class="st">(Long Beach Animal Shelter, 2017–2024)"</span>) <span class="sc">+</span> </span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb43-16"><a href="#cb43-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_pomological</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lbas_eda_reg_likar_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(sex, sterilised)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 3
  sex     sterilised     n
  &lt;chr&gt;   &lt;chr&gt;      &lt;int&gt;
1 Female  No          6230
2 Female  Yes         4763
3 Male    No          6854
4 Male    Yes         5588
5 Unknown Unknown     6352</code></pre>
</div>
</div>
<p>Using the proportion graph, we can see that approximately equal proportion (~43%) of both biological sexes is sterilized. From the count/column graph, we can see that males are more frequently taken in at the animal shelter. 6352 animals have unknown sex and/or sterilization status.</p>
<p>At this point we could plot <code>sex</code> and <code>sterilisation</code> in assocation with previously handled variables - <code>intake_condition</code> and <code>animal_type</code>. I will select only one at this point and then mode on to other variables. I choose <code>animal_type</code> to see whether animals, especially the most frequent ones, differ in their sterilization rate and sex. I will focus on proportions, as we have clearly established thus far that dogs and cats are by far the most dominant animal types and visualization of other types besides them is much more informative in proportions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(animal_type, sex) <span class="sc">%&gt;%</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(animal_type, n, <span class="at">fill =</span> sex) <span class="sc">%&gt;%</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span> </span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="co">#geom_col() + </span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Proportion of animals"</span>, <span class="at">x =</span> <span class="st">"Animal type"</span>, <span class="at">fill =</span> <span class="st">"Sex"</span>, <span class="at">title =</span> <span class="st">"Proportion of different sexes for each type of animal </span><span class="sc">\n</span><span class="st">(Long Beach Animal Shelter, 2017–2024)"</span>) <span class="sc">+</span> </span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_pomological</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lbas_eda_reg_likar_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can see that in exotic animals, birds, wildlife and others, very high proportion of those groups have unknown sex. It seems reasonable to assume that this could happen due to accurate genitalia identification is much more difficult to do in these groups, compared to cats, dogs and small mammals. In those groups, male and female sex appear to be approximately balanced. About 10% of cats and small mammals have unknown sex. About 60% of dogs are males and the rest are mostly females and unknown representatives in very small percentage.</p>
<p>Let’s look at <code>sterilised</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(animal_type, sterilised) <span class="sc">%&gt;%</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(animal_type, n, <span class="at">fill =</span> sterilised) <span class="sc">%&gt;%</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span> </span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>  <span class="co">#geom_col() + </span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Proportion of animals"</span>, <span class="at">x =</span> <span class="st">"Animal type"</span>, <span class="at">fill =</span> <span class="st">"Sterilised"</span>, <span class="at">title =</span> <span class="st">"Proportion of sterilised individuals for each type of animal </span><span class="sc">\n</span><span class="st">(Long Beach Animal Shelter, 2017–2024)"</span>) <span class="sc">+</span></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_pomological</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lbas_eda_reg_likar_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>High percentage of individuals with unknown sterilization status in exotic, birds, wildlife and other could be expected. We have seen in previous analysis that a noticeable proportion of those animals are wild animals, thus there is probably no record kept about their sterilization status. Additionally, as mentioned before identification of genitalia and related markers is much more difficult in these species. For cats, dogs and small mammals, sterilization rate is around 40-50%. We can infer some information from this.</p>
<p>If animals have already been taken to a shelter before, they were most likely sterilized, as this is a standard procedure during the capture and stay. While approximately a half of the animals therefore seem to have been captured before, or surrendered/escaped by/from the owner, who put them through the procedure, about the half of these animals have not been sterilized, implying this is their first time in the shelter and are arguably very young. I could explore this further by creating tile plots with <code>intake_type</code> and count on axes, and <code>sterilisation</code> as fill, faceted for animal types. It would also be possible to perform statistical tests (chi-square) to investigate whether there are significant differences in sterilized vs.&nbsp;unsterilized individuals among different intake or animal types.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(longbeach)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   animal_id      animal_name           animal_type         primary_color 
 A637086:    8   *      :   92   Exotic       :  347   black       :7540  
 A637269:    7   luna   :   84   Birds        : 2075   gray        :3916  
 A279626:    6   rocky  :   78   Cats         :14145   white       :3651  
 A610057:    6   max    :   77   Dogs         : 9768   brown       :3531  
 A354875:    5   coco   :   64   Small mammals:  698   brown  tabby:2242  
 A542375:    5   (Other):17230   Other        : 1342   tan         :1393  
 (Other):29750   NA's   :12162   Wildlife     : 1412   (Other)     :7514  
 secondary_color     sex                 dob              intake_date        
 white  : 8344   Length:29787       Min.   :1993-05-28   Min.   :2017-01-01  
 black  : 1902   Class :character   1st Qu.:2016-07-09   1st Qu.:2018-08-10  
 brown  : 1402   Mode  :character   Median :2018-11-01   Median :2020-08-29  
 tan    :  830                      Mean   :2018-08-09   Mean   :2020-11-17  
 gray   :  783                      3rd Qu.:2022-02-01   3rd Qu.:2023-04-19  
 (Other):  922                      Max.   :2031-03-30   Max.   :2024-12-31  
 NA's   :15604                      NA's   :3591                             
          intake_condition          intake_type     intake_subtype 
 Mild physical    : 2285   stray          :21126   otc     :15519  
 Moderate physical: 2119   wildlife       : 4473   field   :11818  
 Severe physical  : 3408   owner surrender: 2615   trap    :  468  
 Normal           :13706   welfare seized :  484   police  :  374  
 Under age/weight : 6590   confiscate     :  399   adoption:  220  
 Other            : 1679   return         :  306   (Other) :  998  
                           (Other)        :  384   NA's    :  390  
  reason_for_intake  outcome_date       
 owner prob:  432   Min.   :2017-01-01  
 move      :  236   1st Qu.:2018-08-18  
 landlord  :  145   Median :2020-09-01  
 cost      :  133   Mean   :2020-11-27  
 no time   :  122   3rd Qu.:2023-04-21  
 (Other)   :  935   Max.   :2024-12-31  
 NA's      :27784   NA's   :177         
                                               crossing    
 7700 E SPRING ST, LONG BEACH, CA 90815            :  251  
 7700 BLK E SPRING ST, LONG BEACH, CA 90815        :   70  
 6400 BLK ATLANTIC AVE, LONG BEACH, CA 90805       :   68  
 3300 BLK SANTA FE AVE, LONG BEACH, CA 90810       :   50  
 7500 BLK E SPRING ST, LONG BEACH, CA 90815        :   50  
 4700 BLK E PACIFIC COAST HWY, LONG BEACH, CA 90804:   45  
 (Other)                                           :29253  
       jurisdiction            outcome_type    outcome_subtype     latitude    
 Long Beach  :25590   rescue         :6680   spcala    : 3784   Min.   :19.30  
 Cerritos    : 2023   adoption       :6290   walkin    : 2857   1st Qu.:33.78  
 Signal Hill :  721   euthanasia     :5451   web       : 2852   Median :33.81  
 Los Alamitos:  531   transfer       :4869   ill severe: 1869   Mean   :33.81  
 Seal Beach  :  373   return to owner:3214   inj severe: 1286   3rd Qu.:33.85  
 (Other)     :  548   (Other)        :3096   (Other)   :13753   Max.   :45.52  
 NA's        :    1   NA's           : 187   NA's      : 3386                  
   longitude       outcome_is_dead was_outcome_alive
 Min.   :-122.70   Mode :logical   Mode :logical    
 1st Qu.:-118.19   FALSE:23573     FALSE:6214       
 Median :-118.17   TRUE :6214      TRUE :23573      
 Mean   :-118.15                                    
 3rd Qu.:-118.13                                    
 Max.   : -73.99                                    
                                                    
                     geopoint      sterilised       
 33.8096122, -118.0826161:  456   Length:29787      
 33.7700504, -118.1937395:  135   Class :character  
 33.8708354, -118.1846106:  118   Mode  :character  
 33.8097185, -118.0929813:  108                     
 33.7898537, -118.1458794:  101                     
 33.810379, -118.0992327 :   73                     
 (Other)                 :28796                     </code></pre>
</div>
</div>
<p><em>in case data is overwritten, copy here</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co">#longbeach_after_sex &lt;- longbeach</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="co">#longbeach &lt;- longbeach_after_sex</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="outcome-type" class="level3">
<h3 class="anchored" data-anchor-id="outcome-type">Outcome type</h3>
<p>I will proceed to the next variable, <code>outcome_type</code>. Let’s see what are the levels of the variable and how we could collapse, lump them.</p>
<p>I decide for keeping all the outcomes that are at least 2.5% of the complete sample and lump others. in case of condition “shelter, neuter, return” I am not completely sure what it means as different webpages have different interpretations depending on the context. I will therefore collapse this category with “others”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>longbeach <span class="ot">&lt;-</span> longbeach <span class="sc">%&gt;%</span> </span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">outcome_type =</span> <span class="fu">fct_lump</span>(outcome_type,  <span class="at">prop =</span> .<span class="dv">025</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">outcome_type =</span> <span class="fu">fct_collapse</span>(outcome_type,</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">Adoption =</span> <span class="st">"adoption"</span>,</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">Rescue =</span> <span class="st">"rescue"</span>,</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">`</span><span class="at">Return to owner</span><span class="st">`</span> <span class="ot">=</span> <span class="st">"return to owner"</span>,</span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">Euthanasia =</span> <span class="st">"euthanasia"</span>,</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">Died =</span> <span class="st">"died"</span>,</span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">Transfer =</span> <span class="st">"transfer"</span>,</span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">other_level =</span> <span class="st">"Other"</span>))</span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a>                                     </span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span></span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(outcome_type, <span class="at">sort =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 2
  outcome_type        n
  &lt;fct&gt;           &lt;int&gt;
1 Rescue           6680
2 Adoption         6290
3 Euthanasia       5451
4 Transfer         4869
5 Return to owner  3214
6 Other            2333
7 Died              763
8 &lt;NA&gt;              187</code></pre>
</div>
</div>
<p>Let’s now create a column <code>adopted</code>. It will be “Yes” in case of outcome type “adoption” and “No” for all the other outcome types. <strong>At this point, I remove 187 rows from the dataset, as they hame missing values for <code>outcome_type</code>.</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>longbeach <span class="ot">&lt;-</span> longbeach <span class="sc">%&gt;%</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(outcome_type)) <span class="sc">%&gt;%</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">adopted =</span> <span class="fu">ifelse</span>(outcome_type <span class="sc">==</span> <span class="st">"Adoption"</span>, <span class="dv">1</span>, <span class="dv">0</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">adopted =</span> <span class="fu">factor</span>(adopted, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Yes"</span>, <span class="st">"No"</span>)))</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>longbeach <span class="ot">&lt;-</span> longbeach <span class="sc">%&gt;%</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">relocate</span>(adopted, <span class="at">.after =</span> <span class="st">"outcome_type"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s also create a binary + other category <code>outcome_type_posneg</code> where we will collapse <code>outcome_type</code> into positive if animal survived, negative if it did not and other for other level(s).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>longbeach <span class="ot">&lt;-</span> longbeach <span class="sc">%&gt;%</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">outcome_type_posneg =</span> <span class="fu">fct_collapse</span>(outcome_type,</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">Positive =</span> <span class="fu">c</span>(<span class="st">"Adoption"</span>, <span class="st">"Rescue"</span>, <span class="st">"Return to owner"</span>, <span class="st">"Transfer"</span>),</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">Negative =</span> <span class="fu">c</span>(<span class="st">"Died"</span>, <span class="st">"Euthanasia"</span>),</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">other_level =</span> <span class="st">"Other"</span>))</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span></span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">diff =</span> (outcome_type_posneg <span class="sc">==</span> <span class="st">"Positive"</span>) <span class="sc">!=</span> was_outcome_alive) <span class="sc">%&gt;%</span></span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(diff) <span class="sc">%&gt;%</span></span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(outcome_type, was_outcome_alive)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  outcome_type was_outcome_alive     n
  &lt;fct&gt;        &lt;lgl&gt;             &lt;int&gt;
1 Other        TRUE               2333</code></pre>
</div>
</div>
<p>There was a discrepancy in number of my “positive outcomes” and original “alive” outcome in variable <code>was_outcome_alive.</code> I checked what are outcome types in my active dataset that are alive, but are not “positive” in newly created <code>outcome_type_posneg</code> column. All of them are in “other” outcome type. Maybe we can filter out others in future visualization and analysis.</p>
<p>OK! Let’s finally proceed to plotting <code>outcome_type</code> distribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>outcome_type_posneg_colors <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Positive"</span> <span class="ot">=</span> <span class="st">"#4c9b82"</span>,</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Negative"</span> <span class="ot">=</span> <span class="st">"#e15859"</span>,</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Other"</span> <span class="ot">=</span> <span class="st">"#ebcb2a"</span>)</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span> </span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(outcome_type) <span class="sc">%&gt;%</span></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">outcome_type_posneg =</span> <span class="fu">first</span>(outcome_type_posneg)) <span class="sc">%&gt;%</span></span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">outcome_type =</span> <span class="fu">fct_reorder</span>(outcome_type, n)) <span class="sc">%&gt;%</span> </span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> outcome_type, <span class="at">y =</span> n, <span class="at">fill =</span> outcome_type_posneg)) <span class="sc">+</span> </span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span> </span>
<span id="cb56-13"><a href="#cb56-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb56-14"><a href="#cb56-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span> </span>
<span id="cb56-15"><a href="#cb56-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Outcome type"</span>, <span class="at">y =</span> <span class="st">"Number of animals"</span>, <span class="at">title =</span> <span class="st">"Number of animals by outcome type (Long Beach Animal Shelter, 2017–2024)"</span>, <span class="at">fill =</span> <span class="st">"Outcome type"</span>) <span class="sc">+</span> </span>
<span id="cb56-16"><a href="#cb56-16" aria-hidden="true" tabindex="-1"></a>  <span class="co">#scale_y_continuous(breaks = seq(0,15000,2500)) + </span></span>
<span id="cb56-17"><a href="#cb56-17" aria-hidden="true" tabindex="-1"></a>  <span class="co">#scale_fill_brewer(palette = "Spectral", guide = guide_legend(reverse = TRUE)) +</span></span>
<span id="cb56-18"><a href="#cb56-18" aria-hidden="true" tabindex="-1"></a>  <span class="co">#scale_fill_dutchmasters(palette = "milkmaid") + </span></span>
<span id="cb56-19"><a href="#cb56-19" aria-hidden="true" tabindex="-1"></a>  <span class="co">#scale_fill_pomological() + </span></span>
<span id="cb56-20"><a href="#cb56-20" aria-hidden="true" tabindex="-1"></a>  <span class="co">#scale_fill_paletteer_d("PrettyCols::Autumn") +</span></span>
<span id="cb56-21"><a href="#cb56-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> outcome_type_posneg_colors) <span class="sc">+</span></span>
<span id="cb56-22"><a href="#cb56-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title.position =</span> <span class="st">"plot"</span>,</span>
<span id="cb56-23"><a href="#cb56-23" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.3</span>),</span>
<span id="cb56-24"><a href="#cb56-24" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position=</span><span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lbas_eda_reg_likar_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Consider removing the legend</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This could be a nice lollipop plot!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span> </span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(outcome_type) <span class="sc">%&gt;%</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">outcome_type_posneg =</span> <span class="fu">first</span>(outcome_type_posneg)) <span class="sc">%&gt;%</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">proportion =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n),  </span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">label =</span> scales<span class="sc">::</span><span class="fu">percent</span>(proportion, <span class="at">accuracy =</span> <span class="fl">0.1</span>),</span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">outcome_type =</span> <span class="fu">fct_reorder</span>(outcome_type, n) </span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> n, <span class="at">y =</span> outcome_type)) <span class="sc">+</span> </span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">0</span>, <span class="at">xend =</span> n, <span class="at">yend =</span> outcome_type, <span class="at">color =</span> outcome_type_posneg), <span class="at">linewidth =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> outcome_type_posneg), <span class="at">size =</span> <span class="dv">13</span>) <span class="sc">+</span></span>
<span id="cb58-13"><a href="#cb58-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> label), <span class="at">color =</span> <span class="st">"#313131"</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">fontface =</span> <span class="st">"bold"</span>) <span class="sc">+</span></span>
<span id="cb58-14"><a href="#cb58-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb58-15"><a href="#cb58-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="cn">NULL</span>, <span class="at">x =</span> <span class="st">"Number of animals"</span>,</span>
<span id="cb58-16"><a href="#cb58-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Proportion of animals by outcome type (Long Beach Animal Shelter, 2017–2024)"</span>,</span>
<span id="cb58-17"><a href="#cb58-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Outcomes with animal remaining alive and considered positive in green.</span><span class="sc">\n</span><span class="st">Negative outcomes with animals dying in red."</span>,</span>
<span id="cb58-18"><a href="#cb58-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Outcome type"</span>,</span>
<span id="cb58-19"><a href="#cb58-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">"</span><span class="sc">\n</span><span class="st">2333 individuals in group 'other' were originally considered as living outcome. </span><span class="sc">\n</span><span class="st">However after our recoding they were recoded to neither positive nor negative outcome"</span></span>
<span id="cb58-20"><a href="#cb58-20" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span> </span>
<span id="cb58-21"><a href="#cb58-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">7100</span>) <span class="sc">+</span> </span>
<span id="cb58-22"><a href="#cb58-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb58-23"><a href="#cb58-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb58-24"><a href="#cb58-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title.position =</span> <span class="st">"plot"</span>,</span>
<span id="cb58-25"><a href="#cb58-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">0</span>),</span>
<span id="cb58-26"><a href="#cb58-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"none"</span></span>
<span id="cb58-27"><a href="#cb58-27" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span> </span>
<span id="cb58-28"><a href="#cb58-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> outcome_type_posneg_colors)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lbas_eda_reg_likar_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="combining-animal-type-intake-condition-and-outcome-type" class="level3">
<h3 class="anchored" data-anchor-id="combining-animal-type-intake-condition-and-outcome-type">Combining animal type, intake condition and outcome type</h3>
<p>Data allows me to plot more specific associations that I am looking to investigate with regression models. First, we will do three things with broader <code>outcome_type</code> variable:</p>
<ul>
<li>Visualize animal type vs.&nbsp;outcome type</li>
<li>Visualize intake condition vs.&nbsp;outcome type</li>
<li>Tile plot - intake condition vs.&nbsp;animal type, values = proportions with positive outcome</li>
</ul>
<p>Let’s get right to it!</p>
<section id="animal-type-vs.-outcome-type" class="level4">
<h4 class="anchored" data-anchor-id="animal-type-vs.-outcome-type">Animal type vs.&nbsp;outcome type</h4>
<p>Let’s first determine color scale, that will be used for outcomes in all visualizations equally.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>outcome_type_colors <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Adoption"</span> <span class="ot">=</span> <span class="st">"#4c9b82"</span>,</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Return to owner"</span> <span class="ot">=</span> <span class="st">"#6cc08b"</span>,</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Euthanasia"</span> <span class="ot">=</span> <span class="st">"#e76254"</span>,</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Died"</span> <span class="ot">=</span> <span class="st">"#ef8a48"</span>,</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Rescue"</span> <span class="ot">=</span> <span class="st">"#90d890"</span>,</span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Transfer"</span> <span class="ot">=</span> <span class="st">"#d3f2a3"</span>,</span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Other"</span> <span class="ot">=</span> <span class="st">"#acacab"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Animal type vs.&nbsp;outcome type - investigate whether certain animal types are associated with specific outcomes (e.g.&nbsp;cats getting adopted, dogs being transferred etc.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(animal_type, outcome_type) <span class="sc">%&gt;%</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">animal_type =</span> <span class="fu">fct_reorder</span>(animal_type, n, <span class="at">.fun =</span> sum)) <span class="sc">%&gt;%</span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">outcome_type =</span> <span class="fu">fct_relevel</span>(outcome_type,</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">"Euthanasia"</span>,</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">"Died"</span>,</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">"Other"</span>,</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">"Transfer"</span>,</span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">"Rescue"</span>,</span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">"Return to owner"</span>,</span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">"Adoption"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(animal_type, n, <span class="at">fill =</span> outcome_type) <span class="sc">+</span></span>
<span id="cb60-14"><a href="#cb60-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span> </span>
<span id="cb60-15"><a href="#cb60-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span> </span>
<span id="cb60-16"><a href="#cb60-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb60-17"><a href="#cb60-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Animal type"</span>, <span class="at">y =</span> <span class="st">"Proportion of animals with a certain outcome (%)"</span>, <span class="at">fill =</span> <span class="st">"Outcome type"</span>, <span class="at">title =</span> <span class="st">"Proportions of different outcomes for different animal types (Long Beach Animal Shelter, 2017–2024"</span>) <span class="sc">+</span> </span>
<span id="cb60-18"><a href="#cb60-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb60-19"><a href="#cb60-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">labels =</span> <span class="fu">label_percent</span>(), </span>
<span id="cb60-20"><a href="#cb60-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.2</span>),</span>
<span id="cb60-21"><a href="#cb60-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">sec.axis =</span> <span class="fu">dup_axis</span>(<span class="at">labels =</span> <span class="fu">label_percent</span>(), <span class="at">name =</span> <span class="cn">NULL</span>)) <span class="sc">+</span></span>
<span id="cb60-22"><a href="#cb60-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb60-23"><a href="#cb60-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title.position =</span> <span class="st">"plot"</span>,</span>
<span id="cb60-24"><a href="#cb60-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb60-25"><a href="#cb60-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> outcome_type_colors, <span class="at">guide =</span> <span class="fu">guide_legend</span>(<span class="at">reverse =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lbas_eda_reg_likar_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>There are a few things we can conclude from this visualization. Small mammals have the highest proportion of adoptions, followed closely by dogs and cats. While a insignificant proportion of cats is returned to the owners, situation is different for dogs. About 30% of dogs are returned to their owner. It is possible that a significant percentage of stray dogs have escaped their home and were roaming free for a while and then returned to their owner. On the other hand it is possible that much lower proportion of stray cats have escaped their home recently, but are actually street-based animals. Overall, proportion of animals euthanized is about 2.5x higher for cats than for dogs. Highest proportion of euthanasia in a specific animal type is in wildlife (~60%) and animals classified as “other”(~50%). We have speculated in the previous chapters that wildlife animals perhaps end up in the shelter more frequently because of their high rate of moderate and severe injuries (50-55% combined; reported in section “Combining animal type and intake condition”). It is possible that if big proportion of these animals cannot get better, be healed, they highly likely end up euthanized instead of returned to natural habitat.</p>
<p>While positive outcomes (bar segments in green) are about 90% for dogs, 80% for small mammals, 80% for exotic animals, 65% for cats and slightly above 60% for birds, wildlife animals and others are more likely to result in a negative outcome (55% for others, 65% for wildlife).</p>
</section>
<section id="intake-condition-vs.-outcome-type" class="level4">
<h4 class="anchored" data-anchor-id="intake-condition-vs.-outcome-type">Intake condition vs.&nbsp;outcome type</h4>
<p>I will now repeat the same procedure as in the previous section to invastigate possible associations between intake condition and outcome type. With this, we will be able to get some information whether the condition in which the animal is taken into the shelter can give the caretakers any approximation about the most likely outcome for that animal.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(intake_condition, outcome_type) <span class="sc">%&gt;%</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">intake_condition =</span> <span class="fu">fct_relevel</span>(intake_condition,</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Normal"</span>,</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Under age/weight"</span>,</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Mild physical"</span>,</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Moderate physical"</span>,</span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Severe physical"</span>,</span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Other"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">outcome_type =</span> <span class="fu">fct_relevel</span>(outcome_type,</span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">"Euthanasia"</span>,</span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">"Died"</span>,</span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">"Other"</span>,</span>
<span id="cb61-14"><a href="#cb61-14" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">"Transfer"</span>,</span>
<span id="cb61-15"><a href="#cb61-15" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">"Rescue"</span>,</span>
<span id="cb61-16"><a href="#cb61-16" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">"Return to owner"</span>,</span>
<span id="cb61-17"><a href="#cb61-17" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">"Adoption"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb61-18"><a href="#cb61-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb61-19"><a href="#cb61-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(intake_condition, n, <span class="at">fill =</span> outcome_type) <span class="sc">+</span></span>
<span id="cb61-20"><a href="#cb61-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span> </span>
<span id="cb61-21"><a href="#cb61-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span> </span>
<span id="cb61-22"><a href="#cb61-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb61-23"><a href="#cb61-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Intake"</span>, <span class="at">y =</span> <span class="st">"Proportion of animals (%)"</span>, <span class="at">fill =</span> <span class="st">"Outcome type"</span>, <span class="at">title =</span> <span class="st">"Proportions of specific outcome for different intake conditions (Long Beach Animal Shelter, 2017–2024)"</span>) <span class="sc">+</span> </span>
<span id="cb61-24"><a href="#cb61-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb61-25"><a href="#cb61-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">labels =</span> <span class="fu">label_percent</span>(), </span>
<span id="cb61-26"><a href="#cb61-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.2</span>),</span>
<span id="cb61-27"><a href="#cb61-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">sec.axis =</span> <span class="fu">dup_axis</span>(<span class="at">labels =</span> <span class="fu">label_percent</span>(), <span class="at">name =</span> <span class="cn">NULL</span>)) <span class="sc">+</span></span>
<span id="cb61-28"><a href="#cb61-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb61-29"><a href="#cb61-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title.position =</span> <span class="st">"plot"</span>,</span>
<span id="cb61-30"><a href="#cb61-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb61-31"><a href="#cb61-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> outcome_type_colors, <span class="at">guide =</span> <span class="fu">guide_legend</span>(<span class="at">reverse =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lbas_eda_reg_likar_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From this plot we can see that intake condition is associated with the outcome. Almost 90% of animals taken in in normal condition are likely to face a positive outcome, meaning they will stay alive and either get adopted, returned to their owner or be transferred to another rescue or shelter facility. With increase in severity of physical condition, the chances of positive outcome decrease, with about 70% positive outcomes for under-age and/or under-weight animals, and those with mild physical condition. About 55% of animals in moderate physical condition will face a positive outcome and this proportion drops to about 25% for severely injured of ill animals.</p>
</section>
<section id="animal-type-vs.-intake-condition-vs.-outcome-type" class="level4">
<h4 class="anchored" data-anchor-id="animal-type-vs.-intake-condition-vs.-outcome-type">Animal type vs.&nbsp;intake condition vs.&nbsp;outcome type</h4>
<p>Let’s now connect all three variables in a tile plot. I will plot animal type against intake condition and use gradient of the tiles to show what is the percentage of positive vs negative outcome. We will not use specific <code>outcome_type</code> categories, but return to the variable <code>outcome_type_posneg</code>. As a reminder, we collapsed <code>outcome_type</code> categories into positive outcome if animal survived, negative if it did not and other for other level(s). Positive outcomes correspond with green segments and negative outcomes with red in previous graphs in this section.</p>
<p>Note: proportion was calculated as positive / positive + negative + other. Therefore it is crucial to notice that proportional graphs tell us about proportion of positive outcomes compared to negative and other outcomes, not just negative. Other outcomes are significantly lower in count compared to negative however</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span> </span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(intake_condition <span class="sc">!=</span> <span class="st">"Other"</span> <span class="sc">&amp;</span> animal_type <span class="sc">!=</span> <span class="st">"Other"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># count outcome +/- based on intake condition for every animal</span></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(animal_type, intake_condition, outcome_type_posneg) <span class="sc">%&gt;%</span>                       </span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(animal_type, intake_condition) <span class="sc">%&gt;%</span></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>  <span class="co">#calculate total outcomes for each income condition for each animal type and proportion (e.g., positive outcomes for normal cats/ all outcomes for normal cats)</span></span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">outcome_type_total_posnegother =</span> <span class="fu">sum</span>(n),</span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">positive_outcome_type_prop =</span> n<span class="sc">/</span>outcome_type_total_posnegother) <span class="sc">%&gt;%</span></span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># add total number of ouccomes/cases for every animal type</span></span>
<span id="cb62-11"><a href="#cb62-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(animal_type) <span class="sc">%&gt;%</span></span>
<span id="cb62-12"><a href="#cb62-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">total_animal_count =</span> <span class="fu">sum</span>(n)) <span class="sc">%&gt;%</span></span>
<span id="cb62-13"><a href="#cb62-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb62-14"><a href="#cb62-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># add total number of outcomes/cases for every intake condition</span></span>
<span id="cb62-15"><a href="#cb62-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(intake_condition) <span class="sc">%&gt;%</span></span>
<span id="cb62-16"><a href="#cb62-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">intake_condition_total =</span> <span class="fu">sum</span>(n)) <span class="sc">%&gt;%</span></span>
<span id="cb62-17"><a href="#cb62-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb62-18"><a href="#cb62-18" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add new column with animal types and with their total count in brackets and relevel/reorder them in the same step</span></span>
<span id="cb62-19"><a href="#cb62-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">animal_type_label =</span> <span class="fu">fct_reorder</span>(<span class="fu">paste0</span>(animal_type, <span class="st">" ("</span>, total_animal_count, <span class="st">")"</span>),</span>
<span id="cb62-20"><a href="#cb62-20" aria-hidden="true" tabindex="-1"></a>                                         total_animal_count)) <span class="sc">%&gt;%</span></span>
<span id="cb62-21"><a href="#cb62-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">intake_condition =</span> <span class="fu">fct_relevel</span>(intake_condition,</span>
<span id="cb62-22"><a href="#cb62-22" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Normal"</span>,</span>
<span id="cb62-23"><a href="#cb62-23" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Under age/weight"</span>,</span>
<span id="cb62-24"><a href="#cb62-24" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Mild physical"</span>,</span>
<span id="cb62-25"><a href="#cb62-25" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Moderate physical"</span>,</span>
<span id="cb62-26"><a href="#cb62-26" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Severe physical"</span>,</span>
<span id="cb62-27"><a href="#cb62-27" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Other"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb62-28"><a href="#cb62-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(outcome_type_posneg <span class="sc">==</span> <span class="st">"Positive"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb62-29"><a href="#cb62-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb62-30"><a href="#cb62-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb62-31"><a href="#cb62-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> animal_type_label, <span class="at">y =</span> intake_condition, <span class="at">fill =</span> positive_outcome_type_prop<span class="sc">*</span><span class="dv">100</span>) <span class="sc">+</span></span>
<span id="cb62-32"><a href="#cb62-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>(<span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span> </span>
<span id="cb62-33"><a href="#cb62-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(n, <span class="st">"</span><span class="sc">\n</span><span class="st">("</span>, outcome_type_total_posnegother, <span class="st">")"</span>)), <span class="at">color =</span> <span class="st">"#313131"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span> </span>
<span id="cb62-34"><a href="#cb62-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb62-35"><a href="#cb62-35" aria-hidden="true" tabindex="-1"></a>  <span class="co">#coord_fixed() + </span></span>
<span id="cb62-36"><a href="#cb62-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradientn</span>(</span>
<span id="cb62-37"><a href="#cb62-37" aria-hidden="true" tabindex="-1"></a>    <span class="at">colors =</span> <span class="fu">c</span>(<span class="st">"#e76254"</span>, <span class="st">"#ef8a48"</span>, <span class="st">"#fbd587"</span>, <span class="st">"white"</span>,<span class="st">"#d3f2a3"</span>, <span class="st">"#90d890"</span>, <span class="st">"#4c9b82"</span>),</span>
<span id="cb62-38"><a href="#cb62-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">label_percent</span>(<span class="at">scale =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb62-39"><a href="#cb62-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Intake condition of the animal"</span>, <span class="at">title =</span> <span class="st">"Positive outcome proportion for each animal type and intake condition (Long Beach Animal Shelter, 2017–2024)"</span>, <span class="at">subtitle =</span> <span class="st">"Numbers on tiles represent total number of positive outcomes for that intake condition in each animal type.</span><span class="sc">\n</span><span class="st">Number in paranthesis is total number of individuals from that animal type with specific intake condition."</span>, <span class="at">fill =</span> <span class="st">"Positive outcome rate </span><span class="sc">\n</span><span class="st">"</span>) <span class="sc">+</span> </span>
<span id="cb62-40"><a href="#cb62-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb62-41"><a href="#cb62-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lbas_eda_reg_likar_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>There are several important pieces of information we can gather from this plot. First thing to highlight is that across different animal types we can see decrease in positive outcome proportion between mild and severe physical conditions, as gradient goes from greenish to reddish colors. This is especially noticeable in cats, dogs and small mammals. However, it seems that physical conditions have a more pronounced effect in cats compared to dogs. Generally a lower proportion of positive outcomes is observed across different physical conditions for cats compared to dogs. In general, dogs appear to have the highest positive outcome rate, as more than 50% positive outcomes are expected across all conditions except severe physical. On the other hand, wildlife animals face a positive outcome less than 50% of time across all intake conditions, as indicated by dominantly orange-red colored tiles.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span> </span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(intake_condition <span class="sc">!=</span> <span class="st">"Other"</span> <span class="sc">&amp;</span> animal_type <span class="sc">!=</span> <span class="st">"Other"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(animal_type)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  animal_type       n
  &lt;fct&gt;         &lt;int&gt;
1 Exotic          344
2 Birds          2065
3 Cats          13051
4 Dogs           9045
5 Small mammals   689
6 Wildlife       1408</code></pre>
</div>
</div>
<p>Let’s now repeat this whole section, using adoption instead of broader outcome types.</p>
</section>
</section>
<section id="combining-animal-type-intake-condition-and-adoption" class="level3">
<h3 class="anchored" data-anchor-id="combining-animal-type-intake-condition-and-adoption">Combining animal type, intake condition and adoption</h3>
<p>In this section I will focus on replicating the last plot (tile plot) from the last section. It would not be that interesting to plot <code>animal_type vs adoption</code> and <code>intake_condition vs adoption</code>, because filling the columns by outcome type in the previous section gave us explicit information about adoptions, as one of the column fills referred to this category specifically (dark green on previous plots).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>longbeach <span class="sc">%&gt;%</span> </span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(intake_condition <span class="sc">!=</span> <span class="st">"Other"</span> <span class="sc">&amp;</span> animal_type <span class="sc">!=</span> <span class="st">"Other"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># count outcome +/- based on intake condition for every animal</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(animal_type, intake_condition, adopted, <span class="at">.drop =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span>                       </span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(animal_type, intake_condition) <span class="sc">%&gt;%</span></span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>  <span class="co">#calculate total outcomes for each income condition for each animal type and proportion (e.g., positive outcomes for normal cats/ all outcomes for normal cats)</span></span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">outcome_type_total =</span> <span class="fu">sum</span>(n),</span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">outcome_rate =</span> n<span class="sc">/</span>outcome_type_total,</span>
<span id="cb65-9"><a href="#cb65-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">outcome_rate =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(outcome_rate), <span class="dv">0</span>, outcome_rate)) <span class="sc">%&gt;%</span></span>
<span id="cb65-10"><a href="#cb65-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb65-11"><a href="#cb65-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># add total number of outcomes/cases for every animal type</span></span>
<span id="cb65-12"><a href="#cb65-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(animal_type) <span class="sc">%&gt;%</span></span>
<span id="cb65-13"><a href="#cb65-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">total_animal_count =</span> <span class="fu">sum</span>(n)) <span class="sc">%&gt;%</span></span>
<span id="cb65-14"><a href="#cb65-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb65-15"><a href="#cb65-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># add total number of outcomes/cases for every intake condition</span></span>
<span id="cb65-16"><a href="#cb65-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(intake_condition) <span class="sc">%&gt;%</span></span>
<span id="cb65-17"><a href="#cb65-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">intake_condition_total =</span> <span class="fu">sum</span>(n)) <span class="sc">%&gt;%</span></span>
<span id="cb65-18"><a href="#cb65-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb65-19"><a href="#cb65-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add new column with animal types and with their total count in brackets and relevel/reorder them in the same step</span></span>
<span id="cb65-20"><a href="#cb65-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">animal_type_label =</span> <span class="fu">fct_reorder</span>(<span class="fu">paste0</span>(animal_type, <span class="st">" ("</span>, total_animal_count, <span class="st">")"</span>),</span>
<span id="cb65-21"><a href="#cb65-21" aria-hidden="true" tabindex="-1"></a>                                         total_animal_count)) <span class="sc">%&gt;%</span></span>
<span id="cb65-22"><a href="#cb65-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">intake_condition =</span> <span class="fu">fct_relevel</span>(intake_condition,</span>
<span id="cb65-23"><a href="#cb65-23" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Normal"</span>,</span>
<span id="cb65-24"><a href="#cb65-24" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Under age/weight"</span>,</span>
<span id="cb65-25"><a href="#cb65-25" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Mild physical"</span>,</span>
<span id="cb65-26"><a href="#cb65-26" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Moderate physical"</span>,</span>
<span id="cb65-27"><a href="#cb65-27" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Severe physical"</span>,</span>
<span id="cb65-28"><a href="#cb65-28" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Other"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb65-29"><a href="#cb65-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(adopted <span class="sc">==</span> <span class="st">"Yes"</span> <span class="sc">&amp;</span> intake_condition <span class="sc">!=</span> <span class="st">"Other"</span> <span class="sc">&amp;</span> animal_type <span class="sc">!=</span> <span class="st">"Other"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb65-30"><a href="#cb65-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb65-31"><a href="#cb65-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb65-32"><a href="#cb65-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> animal_type_label, <span class="at">y =</span> intake_condition, <span class="at">fill =</span> outcome_rate<span class="sc">*</span><span class="dv">100</span>) <span class="sc">+</span></span>
<span id="cb65-33"><a href="#cb65-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>(<span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span> </span>
<span id="cb65-34"><a href="#cb65-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(n, <span class="st">"</span><span class="sc">\n</span><span class="st">("</span>, outcome_type_total, <span class="st">")"</span>)), <span class="at">color =</span> <span class="st">"#313131"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span> </span>
<span id="cb65-35"><a href="#cb65-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradientn</span>(</span>
<span id="cb65-36"><a href="#cb65-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">colors =</span> <span class="fu">c</span>(<span class="st">"#e76254"</span>, <span class="st">"#ef8a48"</span>, <span class="st">"white"</span>,<span class="st">"#d3f2a3"</span>, <span class="st">"#90d890"</span>, <span class="st">"#4c9b82"</span>),</span>
<span id="cb65-37"><a href="#cb65-37" aria-hidden="true" tabindex="-1"></a>    <span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">label_percent</span>(<span class="at">scale =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb65-38"><a href="#cb65-38" aria-hidden="true" tabindex="-1"></a>  <span class="co">#coord_fixed() + </span></span>
<span id="cb65-39"><a href="#cb65-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Intake condition of the animal"</span>, <span class="at">title =</span> <span class="st">"Adoption rate for each animal type and intake condition (Long Beach Animal Shelter, 2017–2024)"</span>, <span class="at">subtitle =</span> <span class="st">"Numbers on tiles represent total number of adoptions for that intake condition in each animal type.</span><span class="sc">\n</span><span class="st">Numbers in paranthesis are total number of individuals from that animal type with specific intake condition."</span>, <span class="at">fill =</span> <span class="st">"Adoption rate"</span>) <span class="sc">+</span> </span>
<span id="cb65-40"><a href="#cb65-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb65-41"><a href="#cb65-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span>  </span>
<span id="cb65-42"><a href="#cb65-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lbas_eda_reg_likar_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Similarly to the previous plot, this one reveals several interesting details about how intake condition is associated with adoption rate in different animal types. Highest rates of adoptions are in normal and mildly physically compromised cats and small mammals. This is followed by normal and mildly physically compromised dogs. We can see a severe decrease in adoption rate from mild to severe physical condition in dogs and cats. In all groups with the exception of cats, under-age and under-weight animals seem to have little to no chances of getting adopted. This suggest that potential future owners possibly believe that raising such an animal will be very difficult, or possibly shelters do not offer these animals for adoption as often. Though in the section “Intake condition vs.&nbsp;outcome type” we could see that about 15% of under-age and/or under-weight animals get adopted. It is possible that majority of those animals are cats, as we can see in this plot tat about 20% of under-age and/or under-weight cats get adopted. As we have seen in the section “Animal type vs.&nbsp;outcome type”, no wildilfe animals get adopted. Birds have a similarly low rate with a few exceptions in compromised groups and 26 normal individuals getting adopted. Adoption rates are small for exotic animals as well, as only 11 normal and 1 per each physically compromised category were adopted.</p>
<p>Overall, there seems to be more of a binary difference in animal type trends, as cats, dogs and small mammals have adoption rates close to 25-30% percent. On the other hand, other groups share similarly low adoption rate at maximum 5%. Intake conditions exhibit more stepwise (linearly) decreasing rates from normal to most severely physically compromised group. Importantly however, mildly injured animals, especially cats and dogs show higher adoption rates compared to under-age and -weight group. This could be due to fewer offerings of these animals by shelter. On the other hand potential adopters might believe that it is easier to help get mildly compromised animal better, than to take care of under-age or -weight individual in the long run.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>df_for_at_intake_adopt_tbl <span class="ot">&lt;-</span> longbeach <span class="sc">%&gt;%</span> </span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(intake_condition <span class="sc">!=</span> <span class="st">"Other"</span> <span class="sc">&amp;</span> animal_type <span class="sc">!=</span> <span class="st">"Other"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># count outcome +/- based on intake condition for every animal</span></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(animal_type, intake_condition, adopted, <span class="at">.drop =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span>                       </span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(animal_type, intake_condition) <span class="sc">%&gt;%</span></span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>  <span class="co">#calculate total outcomes for each income condition for each animal type and proportion (e.g., positive outcomes for normal cats/ all outcomes for normal cats)</span></span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">outcome_type_total =</span> <span class="fu">sum</span>(n),</span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">outcome_rate =</span> n<span class="sc">/</span>outcome_type_total,</span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">outcome_rate =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(outcome_rate), <span class="dv">0</span>, outcome_rate)) <span class="sc">%&gt;%</span></span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb66-11"><a href="#cb66-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># add total number of outcomes/cases for every animal type</span></span>
<span id="cb66-12"><a href="#cb66-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(animal_type) <span class="sc">%&gt;%</span></span>
<span id="cb66-13"><a href="#cb66-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">total_animal_count =</span> <span class="fu">sum</span>(n)) <span class="sc">%&gt;%</span></span>
<span id="cb66-14"><a href="#cb66-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb66-15"><a href="#cb66-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># add total number of outcomes/cases for every intake condition</span></span>
<span id="cb66-16"><a href="#cb66-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(intake_condition) <span class="sc">%&gt;%</span></span>
<span id="cb66-17"><a href="#cb66-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">intake_condition_total =</span> <span class="fu">sum</span>(n)) <span class="sc">%&gt;%</span></span>
<span id="cb66-18"><a href="#cb66-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb66-19"><a href="#cb66-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add new column with animal types and with their total count in brackets and relevel/reorder them in the same step</span></span>
<span id="cb66-20"><a href="#cb66-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">animal_type_label =</span> <span class="fu">fct_reorder</span>(<span class="fu">paste0</span>(animal_type, <span class="st">" ("</span>, total_animal_count, <span class="st">")"</span>),</span>
<span id="cb66-21"><a href="#cb66-21" aria-hidden="true" tabindex="-1"></a>                                         total_animal_count)) <span class="sc">%&gt;%</span></span>
<span id="cb66-22"><a href="#cb66-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">intake_condition =</span> <span class="fu">fct_relevel</span>(intake_condition,</span>
<span id="cb66-23"><a href="#cb66-23" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Normal"</span>,</span>
<span id="cb66-24"><a href="#cb66-24" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Under age/weight"</span>,</span>
<span id="cb66-25"><a href="#cb66-25" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Mild physical"</span>,</span>
<span id="cb66-26"><a href="#cb66-26" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Moderate physical"</span>,</span>
<span id="cb66-27"><a href="#cb66-27" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Severe physical"</span>,</span>
<span id="cb66-28"><a href="#cb66-28" aria-hidden="true" tabindex="-1"></a>                                        <span class="st">"Other"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb66-29"><a href="#cb66-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(adopted <span class="sc">==</span> <span class="st">"Yes"</span> <span class="sc">&amp;</span> intake_condition <span class="sc">!=</span> <span class="st">"Other"</span> <span class="sc">&amp;</span> animal_type <span class="sc">!=</span> <span class="st">"Other"</span>)</span>
<span id="cb66-30"><a href="#cb66-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-31"><a href="#cb66-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-32"><a href="#cb66-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-33"><a href="#cb66-33" aria-hidden="true" tabindex="-1"></a>df_for_at_intake_adopt_tbl <span class="sc">%&gt;%</span></span>
<span id="cb66-34"><a href="#cb66-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">values =</span> <span class="fu">paste0</span>(n,<span class="st">"/"</span>,outcome_type_total, <span class="st">"</span><span class="sc">\n</span><span class="st">("</span>, <span class="fu">round</span>(outcome_rate<span class="sc">*</span><span class="dv">100</span>, <span class="dv">2</span>), <span class="st">"%)"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb66-35"><a href="#cb66-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(animal_type) <span class="sc">%&gt;%</span></span>
<span id="cb66-36"><a href="#cb66-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">animal_type_adopted =</span> <span class="fu">sum</span>(n),</span>
<span id="cb66-37"><a href="#cb66-37" aria-hidden="true" tabindex="-1"></a>         <span class="at">animal_type_adopted_prop =</span> animal_type_adopted<span class="sc">/</span>total_animal_count) <span class="sc">%&gt;%</span></span>
<span id="cb66-38"><a href="#cb66-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 30 × 12
   animal_type intake_condition  adopted     n outcome_type_total outcome_rate
   &lt;fct&gt;       &lt;fct&gt;             &lt;fct&gt;   &lt;int&gt;              &lt;int&gt;        &lt;dbl&gt;
 1 Exotic      Mild physical     Yes         1                 17      0.0588 
 2 Exotic      Moderate physical Yes         1                 10      0.1    
 3 Exotic      Severe physical   Yes         1                 22      0.0455 
 4 Exotic      Normal            Yes        11                292      0.0377 
 5 Exotic      Under age/weight  Yes         0                  3      0      
 6 Birds       Mild physical     Yes         4                429      0.00932
 7 Birds       Moderate physical Yes         1                502      0.00199
 8 Birds       Severe physical   Yes         1                597      0.00168
 9 Birds       Normal            Yes        26                253      0.103  
10 Birds       Under age/weight  Yes         0                284      0      
# ℹ 20 more rows
# ℹ 6 more variables: total_animal_count &lt;int&gt;, intake_condition_total &lt;int&gt;,
#   animal_type_label &lt;fct&gt;, values &lt;chr&gt;, animal_type_adopted &lt;int&gt;,
#   animal_type_adopted_prop &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>